export default {
  home: () => '/',
  classes: () => '/classes',
  settings: {
    index: () => '/settings',
    profile: () => '/settings/profile',
    password: () => '/settings/password',
    passwordForgot: () => '/settings/password/forgot',
    termsOfUse: () => '/settings/terms-of-use',
    privacyPolicy: () => '/settings/privacy-policy',
  },
  signIn: () => '/sign-in',
  signUp: () => '/sign-up',
  signUpForm: () => '/sign-up-form',
  forgotPassword: () => '/forgot-password',
  user: (id?: number | 'me') => `/users/${id || ':id'}`,
  userSavedPosts: () => `/users/me/saved_posts`,
  class: (id?: number) => `/classes/${id || ':id'}`,
  classSavedPosts: (id?: number) => `/classes/${id || ':id'}/saved_posts`,
  studyFlow: (id?: number) => `/studyflows/${id || ':id'}`,
}
